spring:

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:navin
    username: admin
    password:
    driverClassName: org.h2.Driver
    platform: h2
    data: classpath:datosIniciales.sql